### PR TITLE
refactor(luna): update upcoming lesson card

### PR DESCRIPTION
**Pull request by moalidv**
image

### CODE REVIEW

**Comment by neuodev** [comment]
🚀 [Nova](https://nova-48i5pdzqt-litespace-cores-projects.vercel.app) 
🚀 [Luna](https://luna-4relqsz7f-litespace-cores-projects.vercel.app) 
🚀 [Nebula](https://nebula-2ktw12p7h-litespace-cores-projects.vercel.app) 
🚀 [Dashboard](https://dashboard-pgkwcql63-litespace-cores-projects.vercel.app)

**Comment by neuodev** [comment]
🚀 [Nova](https://nova-r68ftmwhl-litespace-cores-projects.vercel.app) 
🚀 [Luna](https://luna-ewdqv0qn4-litespace-cores-projects.vercel.app) 
🚀 [Nebula](https://nebula-o14fq0wn6-litespace-cores-projects.vercel.app) 
🚀 [Dashboard](https://dashboard-mkp1i76ed-litespace-cores-projects.vercel.app)

**Comment by neuodev** [comment]
🚀 [Nova](https://nova-kji5eu3yu-litespace-cores-projects.vercel.app) 
🚀 [Luna](https://luna-dtg1lvzsp-litespace-cores-projects.vercel.app) 
🚀 [Nebula](https://nebula-4rk72w2u9-litespace-cores-projects.vercel.app) 
🚀 [Dashboard](https://dashboard-gg8h2gqfs-litespace-cores-projects.vercel.app)

**Comment by moalidv** [comment]
close this branch and refactor the card in another branch

**Pull request closed without merging**
