### PR TITLE
chore(recorder): removed recorder feat from project

### PR DESCRIPTION
**Pull request by mostafakamar2308**

### CODE REVIEW

**Comment by neuodev** [comment]
🚀 Nova: https://nova-mtsck8559-litespace-cores-projects.vercel.app
🚀 Luna: https://luna-cc08wy4bq-litespace-cores-projects.vercel.app
🚀 Nebula: https://nebula-7agogqkez-litespace-cores-projects.vercel.app

**Comment by neuodev** [comment]
@mostafakamar2308 please review your that there is additional places at which we should remove the recorder.

**Comment by mostafakamar2308** [comment]
> @mostafakamar2308 please review your task. There is additional places at which we should remove any mentioning to recording feature.

On It 😄

**Comment by neuodev** [comment]
🚀 Nova: https://nova-bws53853n-litespace-cores-projects.vercel.app
🚀 Luna: https://luna-5czq64qyn-litespace-cores-projects.vercel.app
🚀 Nebula: https://nebula-r3rzc44mt-litespace-cores-projects.vercel.app

**Comment by neuodev** [comment]
🚀 Nova: https://nova-2edxnv04f-litespace-cores-projects.vercel.app
🚀 Luna: https://luna-fk06ig9uk-litespace-cores-projects.vercel.app
🚀 Nebula: https://nebula-40ljch09t-litespace-cores-projects.vercel.app
🚀 Dashboard: https://dashboard-p1skimhf9-litespace-cores-projects.vercel.app

**Review by neuodev — APPROVED** [review]

**Pull request merged**
